name: Java with Nexus Repository

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.golden-developer.de
          username: github
          password: ${{ secrets.NEXUS_PASSWORT }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=de.golden-developer artifactId=DCB-Core version=${{GITHUB_REF}}
          assets: extension=jar
          filename: ./target/DCB-CORE-${{GITHUB_REF}}.jar