name: Java with Nexus Repository

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Get Target File
        run: ls -ahl
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.golden-developer.de
          username: github
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: DCB-CORE
          coordinates: groupId=de.goldendeveloper artifactId=DCB-Core version=${{ env.RELEASE_VERSION }}
          assets: extension=jar
          filename: ./target/DCB-Core-${{ env.RELEASE_VERSION }}.jar